<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>QwenStudio</AssemblyName>
    <RootNamespace>QwenStudio</RootNamespace>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <Version>1.2.0</Version>
    <Product>Qwen Studio</Product>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>false</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <SatelliteResourceLanguages>ru;en</SatelliteResourceLanguages>
    <TieredPGO>true</TieredPGO>
    <DebugType>none</DebugType>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="app.ico" />
  </ItemGroup>
</Project>
